import SvgGsapGreensock from '@assets/Icons/GsapGreensock';
import SvgLottieFilesLogo from '@assets/Icons/LottieFilesLogo';
import SvgStitches from '@assets/Icons/Stitches';
import SvgStyledComponentsLogo from '@assets/Icons/StyledComponentsLogo';
import SvgVercelLogo from '@assets/Icons/VercelLogo';
import SvgVite from '@assets/Icons/Vite';
import {
  SiAzuredevops,
  SiAzurepipelines,
  SiBlazor,
  SiBun,
  SiCsharp,
  SiCss3,
  SiDiscord,
  SiDocker,
  SiDotenv,
  SiDotnet,
  SiEslint,
  SiFirebase,
  SiFormik,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGraphql,
  SiHtml5,
  SiI18next,
  SiInsomnia,
  SiJavascript,
  SiJest,
  SiJira,
  SiJquery,
  SiJson,
  SiJss,
  SiLeaflet,
  SiLinear,
  SiLinux,
  SiLodash,
  SiMapbox,
  SiMdx,
  SiMicrosoftteams,
  SiMui,
  SiNextdotjs,
  SiNodedotjs,
  SiNotion,
  SiNpm,
  SiOpenai,
  SiPhp,
  SiPlaywright,
  SiPnpm,
  SiPostman,
  SiPrettier,
  SiRadixui,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiRollupdotjs,
  SiShadcnui,
  SiSlack,
  SiStorybook,
  SiTailwindcss,
  SiTestinglibrary,
  SiTypescript,
  SiUmbraco,
  SiVisualstudio,
  SiVisualstudiocode,
  SiVitest,
  SiWebpack,
  SiWindows11,
  SiWindowsterminal,
  SiWordpress,
  SiXamarin,
  SiYarn,
  SiZod,
} from '@icons-pack/react-simple-icons';
import { TechItemProps } from '../pages/Uses/uses.types';

export const USES_LIST: Array<TechItemProps> = [
  {
    iconComponent: SiTypescript,
    name: 'Typescript',
    category: ['lang', 'love', 'using'],
  },
  {
    iconComponent: SiReact,
    name: 'React',
    category: ['framework', 'love', 'using'],
  },
  {
    icon: SvgVite,
    name: 'Vite',
    category: ['framework', 'love', 'using'],
  },
  {
    name: 'Radix UI',
    iconComponent: SiRadixui,
    category: ['ui-ux', 'love', 'using'],
  },
  {
    name: 'Stitches',
    icon: SvgStitches,
    category: ['ui-ux', 'love', 'using'],
  },
  {
    name: 'Lottie',
    icon: SvgLottieFilesLogo,
    category: ['ui-ux', 'love', 'using'],
  },
  {
    name: 'GSAP',
    icon: SvgGsapGreensock,
    category: ['ui-ux', 'love', 'using'],
  },
  {
    name: 'Styled Components',
    icon: SvgStyledComponentsLogo,
    category: ['ui-ux', 'using'],
  },
  {
    name: 'Vercel',
    icon: SvgVercelLogo,
    category: ['cloud', 'love', 'using'],
  },
  {
    name: 'Testing Library',
    iconComponent: SiTestinglibrary,
    category: ['testing', 'love', 'using'],
  },
  {
    name: 'Rollup',
    iconComponent: SiRollupdotjs,
    category: ['bundler', 'love', 'using'],
  },
  {
    name: 'MUI',
    iconComponent: SiMui,
    category: ['ui-ux', 'using'],
  },
  {
    name: 'Next.js',
    iconComponent: SiNextdotjs,
    category: ['framework', 'using'],
  },
  {
    name: 'Tailwind',
    iconComponent: SiTailwindcss,
    category: ['ui-ux', 'not-using'],
  },
  {
    name: 'Node.js',
    iconComponent: SiNodedotjs,
    category: ['framework', 'using', 'hate'],
  },
  {
    name: 'Bun',
    iconComponent: SiBun,
    category: ['framework', 'using', 'love', 'bundler'],
  },
  {
    name: 'Vitest',
    iconComponent: SiVitest,
    category: ['testing', 'using', 'love'],
  },
  {
    name: 'Playwright',
    iconComponent: SiPlaywright,
    category: ['testing', 'using', 'love'],
  },
  {
    name: 'Javascript',
    iconComponent: SiJavascript,
    category: ['lang', 'using'],
  },
  {
    name: 'JSS',
    iconComponent: SiJss,
    category: ['ui-ux', 'using', 'love'],
  },
  {
    name: 'CSS',
    iconComponent: SiCss3,
    category: ['lang', 'using'],
  },
  {
    name: 'OpenAI',
    iconComponent: SiOpenai,
    category: ['web-tool', 'using', 'love'],
  },
  {
    name: 'Linear',
    iconComponent: SiLinear,
    category: ['web-tool', 'not-using', 'love'],
  },
  {
    name: 'VSCode',
    iconComponent: SiVisualstudiocode,
    category: ['env', 'using', 'love'],
  },
  {
    name: 'Visual Studio',
    iconComponent: SiVisualstudio,
    category: ['env', 'not-using', 'hate'],
  },
  {
    name: 'Jira',
    iconComponent: SiJira,
    category: ['web-tool', 'not-using', 'hate'],
  },
  {
    name: 'Git',
    iconComponent: SiGit,
    category: ['cloud', 'using'],
  },
  {
    name: 'Azure',
    iconComponent: SiAzuredevops,
    category: ['cloud', 'web-tool', 'using'],
  },
  {
    name: 'Azure Pipelines',
    iconComponent: SiAzurepipelines,
    category: ['cloud', 'using', 'love'],
  },
  {
    name: 'Gitlab',
    iconComponent: SiGitlab,
    category: ['cloud', 'not-using', 'love'],
  },
  {
    name: 'Github',
    iconComponent: SiGithub,
    category: ['cloud', 'using'],
  },
  {
    name: 'Slack',
    iconComponent: SiSlack,
    category: ['web-tool', 'not-using', 'love'],
  },
  {
    name: 'MS Teams',
    iconComponent: SiMicrosoftteams,
    category: ['web-tool', 'using', 'hate'],
  },
  {
    name: 'Xamarin',
    iconComponent: SiXamarin,
    category: ['framework', 'not-using'],
  },
  {
    name: 'ASP.NET core',
    iconComponent: SiDotnet,
    category: ['framework', 'not-using'],
  },
  {
    name: 'HTML',
    iconComponent: SiHtml5,
    category: ['lang', 'using'],
  },
  {
    name: 'Prettier',
    iconComponent: SiPrettier,
    category: ['framework', 'using'],
  },
  {
    name: 'Eslint',
    iconComponent: SiEslint,
    category: ['framework', 'using', 'love'],
  },
  {
    name: 'I18next',
    iconComponent: SiI18next,
    category: ['framework', 'using'],
  },
  {
    name: 'Storybook',
    iconComponent: SiStorybook,
    category: ['framework', 'testing', 'using', 'love'],
  },
  {
    name: 'Jest',
    iconComponent: SiJest,
    category: ['framework', 'testing', 'not-using'],
  },
  {
    name: 'Notion',
    iconComponent: SiNotion,
    category: ['web-tool', 'using'],
  },
  { name: 'C#', iconComponent: SiCsharp, category: ['lang', 'not-using'] },
  {
    name: 'Bash/Powershell',
    iconComponent: SiWindowsterminal,
    category: ['lang', 'using', 'love'],
  },
  {
    name: 'Firebase',
    iconComponent: SiFirebase,
    category: ['cloud', 'not-using'],
  },
  {
    name: 'Jquery',
    iconComponent: SiJquery,
    category: ['framework', 'not-using'],
  },
  {
    name: 'Blazor',
    iconComponent: SiBlazor,
    category: ['framework', 'not-using', 'hate'],
  },
  {
    name: 'Umbraco',
    iconComponent: SiUmbraco,
    category: ['framework', 'not-using', 'hate'],
  },
  {
    name: 'Wordpress',
    iconComponent: SiWordpress,
    category: ['framework', 'not-using', 'hate'],
  },
  {
    name: 'Docker',
    iconComponent: SiDocker,
    category: ['env', 'not-using', 'love'],
  },
  {
    name: 'yarn',
    iconComponent: SiYarn,
    category: ['framework', 'using'],
  },
  {
    name: 'pnpm',
    iconComponent: SiPnpm,
    category: ['framework', 'using', 'love'],
  },
  {
    name: 'npm',
    iconComponent: SiNpm,
    category: ['framework', 'not-using', 'hate'],
  },
  {
    name: 'Webpack',
    iconComponent: SiWebpack,
    category: ['bundler', 'not-using', 'hate'],
  },
  {
    name: 'Linux',
    iconComponent: SiLinux,
    category: ['env', 'not-using', 'love'],
  },
  {
    name: 'Windows',
    iconComponent: SiWindows11,
    category: ['env', 'using', 'love'],
  },
  {
    name: 'Dotenv',
    iconComponent: SiDotenv,
    category: ['framework', 'using'],
  },
  {
    name: 'Mapbox',
    iconComponent: SiMapbox,
    category: ['framework', 'not-using', 'love'],
  },
  {
    name: 'Leaflet',
    iconComponent: SiLeaflet,
    category: ['framework', 'not-using'],
  },
  {
    name: 'Shadcnui',
    iconComponent: SiShadcnui,
    category: ['ui-ux', 'not-using', 'love'],
  },
  {
    name: 'Graphql',
    iconComponent: SiGraphql,
    category: ['framework', 'not-using', 'love'],
  },
  {
    name: 'MDX',
    iconComponent: SiMdx,
    category: ['lang', 'using'],
  },
  {
    name: 'ZOD',
    iconComponent: SiZod,
    category: ['framework', 'using', 'love'],
  },
  {
    name: 'Lodash',
    iconComponent: SiLodash,
    category: ['framework', 'using', 'love'],
  },
  {
    name: 'React Hook Form',
    iconComponent: SiReacthookform,
    category: ['framework', 'not-using'],
  },
  {
    name: 'React Router',
    iconComponent: SiReactrouter,
    category: ['framework', 'using', 'love'],
  },
  {
    name: 'React Query',
    iconComponent: SiReactquery,
    category: ['framework', 'not-using', 'love'],
  },
  {
    name: 'Insomnia',
    iconComponent: SiInsomnia,
    category: ['web-tool', 'not-using'],
  },
  {
    name: 'Postman',
    iconComponent: SiPostman,
    category: ['web-tool', 'using'],
  },
  { name: 'JSON', iconComponent: SiJson, category: ['lang', 'using'] },
  {
    name: 'Formik',
    iconComponent: SiFormik,
    category: ['framework', 'using'],
  },
  {
    name: 'Discord',
    iconComponent: SiDiscord,
    category: ['web-tool', 'using', 'love'],
  },
  {
    name: 'PHP',
    iconComponent: SiPhp,
    category: ['lang', 'not-using'],
  },
];
